image: "ruby:2.5"

pages:
  stage: deploy
  before_script:
    - ruby -v
    - gem i bundler -v 1.17.3
    - bundle install -j $(nproc) --path vendor
    - if [ -d "public" ]; then rm -r public; fi
  script:
    - bundle exec middleman build --clean
  after_script:
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - master