image: "ruby:2.5"

pages:
  stage: deploy
  before_script:
    - ruby -v
    - gem i bundler -v 1.17.3
    - bundle install -j $(nproc) --path vendor
  script:
    - bundle exec middleman build --clean
  artifacts:
    paths:
    - build
  only:
    - master