image: "ruby:2.5"

pages:
  stage: deploy
  before_script:
    - ruby -v
    - gem i bundler -v 1.17.3
    - bundle install -j $(nproc) --path vendor
  script:
    - bundle exec middleman build --clean
  after_script:
    - if [ -d "build" ]; then rm -r build; fi
    - mv build/* public
  artifacts:
    paths:
    - public
  only:
    - master